// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Verify OTP
export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED';

// Verify BONDS
export const VERIFY_BONDS_REQUEST = 'VERIFY_BONDS_REQUEST';
export const VERIFY_BONDS_SUCCESS = 'VERIFY_BONDS_SUCCESS';
export const VERIFY_BONDS_FAILED = 'VERIFY_BONDS_FAILED';

// market index list
export const MARKET_INDEX_LIST_REQUEST = 'MARKET_INDEX_LIST_REQUEST';
export const MARKET_INDEX_LIST_SUCCESS = 'MARKET_INDEX_LIST_SUCCESS';
export const MARKET_INDEX_LIST_FAILED = 'MARKET_INDEX_LIST_FAILED';

//roomVCSC
export const ROOM_VCSC_REQUEST = 'ROOM_VCSC_REQUEST';
export const ROOM_VCSC_SUCCESS = 'ROOM_VCSC_SUCCESS';
export const ROOM_VCSC_FAILED = 'ROOM_VCSC_FAILED';

//Detail Bonds
export const DETAIL_BOND_REQUEST = 'DETAIL_BOND_REQUEST';
export const DETAIL_BOND_SUCCESS = 'DETAIL_BOND_SUCCESS';
export const DETAIL_BOND_FAILED = 'DETAIL_BOND_FAILED';