// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Verify OTP
export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED';

// get user
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

// Cash balance
export const CASH_BALANCE_REQUEST = 'CASH_BALANCE_REQUEST';
export const CASH_BALANCE_SUCCESS = 'CASH_BALANCE_SUCCESS';
export const CASH_BALANCE_FAILED = 'CASH_BALANCE_FAILED';

// Deduct bank account
export const DEDUCT_BANK_ACCOUNT_REQUEST = 'DEDUCT_BANK_ACCOUNT_REQUEST';
export const DEDUCT_BANK_ACCOUNT_SUCCESS = 'DEDUCT_BANK_ACCOUNT_SUCCESS';
export const DEDUCT_BANK_ACCOUNT_FAILED = 'DEDUCT_BANK_ACCOUNT_FAILED';

// Verify BONDS
export const VERIFY_BONDS_REQUEST = 'VERIFY_BONDS_REQUEST';
export const VERIFY_BONDS_SUCCESS = 'VERIFY_BONDS_SUCCESS';
export const VERIFY_BONDS_FAILED = 'VERIFY_BONDS_FAILED';

// market index list
export const MARKET_INDEX_LIST_REQUEST = 'MARKET_INDEX_LIST_REQUEST';
export const MARKET_INDEX_LIST_SUCCESS = 'MARKET_INDEX_LIST_SUCCESS';
export const MARKET_INDEX_LIST_FAILED = 'MARKET_INDEX_LIST_FAILED';

//roomVCSC
export const ROOM_VCSC_REQUEST = 'ROOM_VCSC_REQUEST';
export const ROOM_VCSC_SUCCESS = 'ROOM_VCSC_SUCCESS';
export const ROOM_VCSC_FAILED = 'ROOM_VCSC_FAILED';

//Detail Bonds
export const DETAIL_BOND_REQUEST = 'DETAIL_BOND_REQUEST';
export const DETAIL_BOND_SUCCESS = 'DETAIL_BOND_SUCCESS';
export const DETAIL_BOND_FAILED = 'DETAIL_BOND_FAILED';

//Buy Bonds from room VCSC
export const BUY_BONDS_ROOM_VCSC_REQUEST = 'BUY_BONDS_ROOM_VCSC_REQUEST';
export const BUY_BONDS_ROOM_VCSC_SUCCESS = 'BUY_BONDS_ROOM_VCSC_SUCCESS';
export const BUY_BONDS_ROOM_VCSC_FAILED = 'BUY_BONDS_ROOM_VCSC_FAILED';

//Get list bonds of investor
export const GET_LIST_BONDS_OF_INVESTOR_REQUEST = 'GET_LIST_BONDS_OF_INVESTOR_REQUEST';
export const GET_LIST_BONDS_OF_INVESTOR_SUCCESS = 'GET_LIST_BONDS_OF_INVESTOR_SUCCESS';
export const GET_LIST_BONDS_OF_INVESTOR_FAILED = 'GET_LIST_BONDS_OF_INVESTOR_FAILED';

//Get list fee trade
export const GET_LIST_FEE_TRADE_REQUEST = 'GET_LIST_FEE_TRADE_REQUEST';
export const GET_LIST_FEE_TRADE_SUCCESS = 'GET_LIST_FEE_TRADE_SUCCESS';
export const GET_LIST_FEE_TRADE_FAILED = 'GET_LIST_FEE_TRADE_FAILED';

//update money asset
export const UPDATE_MONEY_ASSET_REQUEST = 'UPDATE_MONEY_ASSET_REQUEST';
export const UPDATE_MONEY_ASSET_SUCCESS = 'UPDATE_MONEY_ASSET_SUCCESS';
export const UPDATE_MONEY_ASSET_FAILED = 'UPDATE_MONEY_ASSET_FAILED';

//transaction history
export const TRANSACTION_HISTORY_REQUEST = 'TRANSACTION_HISTORY_REQUEST';
export const TRANSACTION_HISTORY_SUCCESS = 'TRANSACTION_HISTORY_SUCCESS';
export const TRANSACTION_HISTORY_FAILED = 'TRANSACTION_HISTORY_FAILED';

//get list interest return trade
export const LIST_INTEREST_RETURN_TRADE_REQUEST = 'LIST_INTEREST_RETURN_TRADE_REQUEST';
export const LIST_INTEREST_RETURN_TRADE_SUCCESS = 'LIST_INTEREST_RETURN_TRADE_SUCCESS';
export const LIST_INTEREST_RETURN_TRADE_FAILED = 'LIST_INTEREST_RETURN_TRADE_FAILED';